apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: deep-work-station-base

resources:
  - namespace.yaml
  - deployment.yaml  
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app: deep-work-station
      version: v1

images:
  - name: deep-work-station
    newName: ghcr.io/j0hnroger/deep-work-station
    newTag: main-75a6538