/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SceneIndexRouteImport } from './routes/scene/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'

const SceneIndexRoute = SceneIndexRouteImport.update({
  id: '/scene/',
  path: '/scene/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeIndexRoute
  '/scene': typeof SceneIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/scene': typeof SceneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home/': typeof HomeIndexRoute
  '/scene/': typeof SceneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/scene'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/scene'
  id: '__root__' | '/home/' | '/scene/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  SceneIndexRoute: typeof SceneIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scene/': {
      id: '/scene/'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  SceneIndexRoute: SceneIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
